NIXPACKS_TOML = """
# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p results",
    "mkdir -p logs"
]

[start]
cmd = "python main.py"

[variables]
PYTHON_VERSION = "3.11"
TZ = "Europe/Berlin"
"""